apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: api
        image: djhony/bilheteria-park-backend:latest
        ports:
        - containerPort: 8000
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10

        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials-secret
                key: password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-credentials-secret
                key: host
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-credentials-secret
                key: dbname
          
          - name: DATABASE_URL
            value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):5432/$(DB_NAME)"
            
          - name: AWS_SQS_QUEUE_URL
            value: "https://sqs.us-east-1.amazonaws.com/SEU_ID_DE_CONTA/nome-da-sua-fila"

          - name: REDIS_URL
            value: "redis://k3s-redis.xxxxxx.cache.amazonaws.com:6379/0"

          - name: ADMIN_USERNAME
            value: "admin"

          - name: ADMIN_PASSWORD
            value: "teste123"
          
          - name: LOG_LEVEL
            value: "INFO"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.tls: "false"
    traefik.ingress.kubernetes.io/router.priority: "100"
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: /eventos
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: /compras
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: /openapi.json
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80